"""
sdlos.assets.gitignore
======================
Per-directory .gitignore content for the data/ skeleton scaffolded by
``sdlos create --data-dir``.

Each constant is a ready-to-write string.  The caller (commands/create.py)
writes it as ``.gitignore`` in the appropriate subdirectory.

Layout
------
DATA_ROOT     — data/.gitignore         (OS artifacts, applies recursively)
IMG           — data/img/.gitignore     (OS artifacts)
MODELS        — data/models/.gitignore  (OS artifacts + Git LFS hint)
SHADERS       — data/shaders/.gitignore (OS artifacts)
SPIRV         — data/shaders/spirv/.gitignore  (OS artifacts + *.spv rule)

Design notes
------------
- No .gitkeep files.  Every directory either has real content (shaders,
  canvas.png) or a .gitignore that keeps it tracked by git.
- The root DATA_ROOT gitignore uses **/ patterns so it applies recursively
  to all subdirectories without needing a separate file in each one.
  Per-subdirectory overrides (MODELS, SPIRV) are placed only where the
  default rule needs to differ.
"""

from __future__ import annotations

# ── Shared OS-artifact patterns ───────────────────────────────────────────────

_OS = """\
# ── OS artifacts ─────────────────────────────────────────────────────────────
.DS_Store
._*
.Spotlight-V100
.Trashes
Thumbs.db
desktop.ini
ehthumbs.db
"""

# ── data/.gitignore ───────────────────────────────────────────────────────────
# Placed at the root of the data/ directory.
# Uses **/ so the rules cascade into every subdirectory automatically.

DATA_ROOT = """\
# sdlos app data — generated by sdlos create
# ─────────────────────────────────────────────────────────────────────────────
# This directory is colocated with the app source and committed to the repo.
# Add your shader sources, images, and model files here.
# Large binary assets (GLB, textures) should use Git LFS:
#   git lfs track "*.glb"
#   git lfs track "*.png"  # if textures are large

# ── OS artifacts (recursive) ─────────────────────────────────────────────────
**/.DS_Store
**/._*
**/.Spotlight-V100
**/.Trashes
**/Thumbs.db
**/desktop.ini
**/ehthumbs.db
"""

# ── data/img/.gitignore ───────────────────────────────────────────────────────

IMG = _OS + """\
# Image files tracked here: .png  .jpg  .jpeg  .webp  .tga  .bmp
# canvas.png is the scaffold placeholder — replace with your own texture.
"""

# ── data/models/.gitignore ────────────────────────────────────────────────────
# Model files can be large; include a Git LFS hint.

MODELS = _OS + """\
# Model files: .glb  .gltf  .obj  .fbx
#
# Large binary assets should use Git LFS to avoid bloating the repository:
#   git lfs track "*.glb"
#   git lfs track "*.gltf"
#   git lfs track "*.fbx"
# Then commit the .gitattributes file that git lfs generates.
"""

# ── data/shaders/.gitignore ───────────────────────────────────────────────────

SHADERS = _OS + """\
# Shader sources are committed.  Compiled bytecode lives in spirv/ and
# is typically excluded (see data/shaders/spirv/.gitignore).
"""

# ── data/shaders/spirv/.gitignore ─────────────────────────────────────────────
# SPIRV bytecode is compiled from shader sources and is usually not tracked.
# The .gitignore keeps the directory in git while excluding compiled output.

SPIRV = _OS + """\
# SPIRV bytecode — compiled from Metal / GLSL sources, not typically tracked.
# To compile MSL shaders to SPIRV with spirv-cross:
#   spirv-cross --msl preset_a.frag.metal --output preset_a.frag.spv
#
# Uncomment the line below to start tracking compiled SPIRV in this repo:
# !*.spv
*.spv
"""
